package model;

import java.io.Serializable;

/**
 * Car 锟斤拷锟絝锟斤拷锟絅锟斤拷锟絏.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class Car implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** carid. */
	private Integer carid;

	/** pinpaiming. */
	private String pinpaiming;

	/** xilie. */
	private String xilie;

	/** gonglishu. */
	private Integer gonglishu;

	/** shoujia. */
	private Integer shoujia;

	/** yanse. */
	private String yanse;

	/** pailiang. */
	private String pailiang;

	/** zhaopian. */
	private String zhaopian;

	/**
	 * 锟絉锟斤拷锟絏锟絞锟斤拷锟絅锟絕.
	 */
	public Car() {
	}

	/**
	 * carid 锟斤拷輶鑲碉拷軅锟�.
	 * 
	 * @param carid
	 *            carid
	 */
	public void setCarid(Integer carid) {
		this.carid = carid;
	}

	/**
	 * carid 锟斤拷锟芥摼锟斤拷锟杰傦拷.
	 * 
	 * @return carid
	 */
	public Integer getCarid() {
		return this.carid;
	}

	/**
	 * pinpaiming 锟斤拷輶鑲碉拷軅锟�.
	 * 
	 * @param pinpaiming
	 *            pinpaiming
	 */
	public void setPinpaiming(String pinpaiming) {
		this.pinpaiming = pinpaiming;
	}

	/**
	 * pinpaiming 锟斤拷锟芥摼锟斤拷锟杰傦拷.
	 * 
	 * @return pinpaiming
	 */
	public String getPinpaiming() {
		return this.pinpaiming;
	}

	/**
	 * xilie 锟斤拷輶鑲碉拷軅锟�.
	 * 
	 * @param xilie
	 *            xilie
	 */
	public void setXilie(String xilie) {
		this.xilie = xilie;
	}

	/**
	 * xilie 锟斤拷锟芥摼锟斤拷锟杰傦拷.
	 * 
	 * @return xilie
	 */
	public String getXilie() {
		return this.xilie;
	}

	/**
	 * gonglishu 锟斤拷輶鑲碉拷軅锟�.
	 * 
	 * @param gonglishu
	 *            gonglishu
	 */
	public void setGonglishu(Integer gonglishu) {
		this.gonglishu = gonglishu;
	}

	/**
	 * gonglishu 锟斤拷锟芥摼锟斤拷锟杰傦拷.
	 * 
	 * @return gonglishu
	 */
	public Integer getGonglishu() {
		return this.gonglishu;
	}

	/**
	 * shoujia 锟斤拷輶鑲碉拷軅锟�.
	 * 
	 * @param shoujia
	 *            shoujia
	 */
	public void setShoujia(Integer shoujia) {
		this.shoujia = shoujia;
	}

	/**
	 * shoujia 锟斤拷锟芥摼锟斤拷锟杰傦拷.
	 * 
	 * @return shoujia
	 */
	public Integer getShoujia() {
		return this.shoujia;
	}

	/**
	 * yanse 锟斤拷輶鑲碉拷軅锟�.
	 * 
	 * @param yanse
	 *            yanse
	 */
	public void setYanse(String yanse) {
		this.yanse = yanse;
	}

	/**
	 * yanse 锟斤拷锟芥摼锟斤拷锟杰傦拷.
	 * 
	 * @return yanse
	 */
	public String getYanse() {
		return this.yanse;
	}

	/**
	 * pailiang 锟斤拷輶鑲碉拷軅锟�.
	 * 
	 * @param pailiang
	 *            pailiang
	 */
	public void setPailiang(String pailiang) {
		this.pailiang = pailiang;
	}

	/**
	 * pailiang 锟斤拷锟芥摼锟斤拷锟杰傦拷.
	 * 
	 * @return pailiang
	 */
	public String getPailiang() {
		return this.pailiang;
	}

	/**
	 * zhaopian 锟斤拷輶鑲碉拷軅锟�.
	 * 
	 * @param zhaopian
	 *            zhaopian
	 */
	public void setZhaopian(String zhaopian) {
		this.zhaopian = zhaopian;
	}

	/**
	 * zhaopian 锟斤拷锟芥摼锟斤拷锟杰傦拷.
	 * 
	 * @return zhaopian
	 */
	public String getZhaopian() {
		return this.zhaopian;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((carid == null) ? 0 : carid.hashCode());

		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		Car other = (Car) obj;
		if (carid == null) {
			if (other.carid != null) {
				return false;
			}
		} else if (!carid.equals(other.carid)) {
			return false;
		}

		return true;
	}

}
